<?php
// HUSK BEDRIFTSVARIABLER

if (!defined('ABSPATH')) {
    exit;
}

$url_options = get_option('kag_seo_option_name');
$kurs = !empty($url_options['ka_url_rewrite_kurs']) ? $url_options['ka_url_rewrite_kurs'] : 'kurs';
$instruktor = !empty($url_options['ka_url_rewrite_instruktor']) ? $url_options['ka_url_rewrite_instruktor'] : 'instruktor';

// CPT Kurs
register_post_type('course', array(
    'labels' => array(
        'name' => 'Kurs',
        'singular_name' => 'Kurs',
        'menu_name' => 'Kurs',
        'all_items' => 'Alle kurs',
        'edit_item' => 'Rediger kurs',
        'view_item' => 'Vis kurs',
        'view_items' => 'Vis kurs',
        'add_new_item' => 'Legg til kurs',
        'add_new' => 'Legg til kurs',
        'new_item' => 'Nytt kurs',
        'parent_item_colon' => 'Overordnet kurs:',
        'search_items' => 'Søk kurs',
        'not_found' => 'Ingen kurs funnet',
        'not_found_in_trash' => 'Ingen kurs funnet i søppelkurven',
        'archives' => 'kursliste',
        'attributes' => 'kursattributter',
        'featured_image' => 'Hovedbilde',
        'set_featured_image' => 'Velg hovedbilde',
        'remove_featured_image' => 'Fjern',
        'use_featured_image' => 'Bruk bilde',
        'insert_into_item' => 'Sett inn',
        'uploaded_to_this_item' => 'Lastet opp til dette kurset',
        'filter_items_list' => 'Filtrer kursliste',
        'filter_by_date' => 'Filtrer på dato',
        'items_list_navigation' => 'naviger i kurs',
        'items_list' => 'Kursliste',
        'item_published' => 'Kurs publisert',
        'item_published_privately' => 'Kurs publisert privat',
        'item_reverted_to_draft' => 'Kurs gjort om til kladd',
        'item_scheduled' => 'Kurs planlagt',
        'item_updated' => 'Kurs oppdatert',
        'item_link' => 'Link',
        'item_link_description' => 'Link til kurs',
    ),
    'public'        => true,
    'has_archive'   => true,
    'show_in_rest'  => true,
    'menu_icon'     => 'dashicons-welcome-learn-more',
    'supports'      => array('title', 'editor', 'excerpt', 'thumbnail','custom-fields','page-attributes'),
    'taxonomies'    => array('coursecategory', 'course_location'),
    'rewrite'       => array('slug' => $kurs, 'with_front' => false),
    'hierarchical'  => true,
    'parent_item_colon' => 'Hovedkurs:',
    'delete_with_user' => false,
));

// CPT Kursdato
register_post_type('coursedate', array(
    'labels' => array(
        'name' => 'Kursdatoer',
        'singular_name' => 'Kursdato',
        'menu_name' => 'Kursdatoer',
        'all_items' => 'Kursdatoer',
        'edit_item' => 'Rediger kursdato',
        'view_item' => 'Vis kursdato',
        'view_items' => 'Vis kursdato',
        'add_new_item' => 'Legg til kursdato',
        'add_new' => 'Legg til kursdato',
        'new_item' => 'Ny kursdato',
        'search_items' => 'Søk i kursdato',
        'not_found' => 'Ingen kursdatoer funnet',
        'not_found_in_trash' => 'Ingen kursdatoer funnet i søppelkurven',
        'archives' => 'kursdato arkiv',
        'attributes' => 'Kursdato attributter',
        'set_featured_image' => 'Velg hovedbilde',
        'remove_featured_image' => 'Fjern hovedbilde',
        'use_featured_image' => 'Bruk som hovedbilde',
        'insert_into_item' => 'Sett inn i kursdato',
        'uploaded_to_this_item' => 'Lastet opp til kursdato',
        'filter_items_list' => 'Filtrer kursdato liste',
        'filter_by_date' => 'Filtrer kursdato på dato',
        'items_list_navigation' => 'Kursdato listenavigasjon',
        'items_list' => 'Kursdato liste',
        'item_published' => 'Kursdato publisert.',
        'item_published_privately' => 'Kursdato publisert privat.',
        'item_reverted_to_draft' => 'Kursdato gjort om til kladd.',
        'item_scheduled' => 'Kursdato planlagt.',
        'item_updated' => 'Kursdato oppdatert.',
        'item_link' => 'Kursdato link',
        'item_link_description' => 'Link til en kursdato.',
    ),
    'public'            => true,
    'has_archive'       => false,
    //'show_in_menu'      => 'edit.php?post_type=kurs',
    'show_in_admin_bar' => true,
    'show_in_rest'      => true,
    'menu_icon'         => 'dashicons-calendar-alt',
    'supports'          => array('title', 'custom-fields', ),
    'taxonomies'        => array( 'kurssted', 'kurskategori' ),
    'rewrite'           => array( 'slug' => 'kursdato', ),
    'delete_with_user'  => false,
));

// CPT Instructor
register_post_type('instructor', array(
    'labels' => array(
        'name' => 'Instruktørprofil',
        'singular_name' => 'Instruktør',
        'menu_name' => 'Instruktørprofiler',
        'all_items' => 'Alle instruktører',
        'edit_item' => 'Rediger instruktør',
        'view_item' => 'Vis instruktør',
        'view_items' => 'Vis instruktør',
        'add_new_item' => 'Legg til instruktør',
        'add_new' => 'Legg til instruktør',
        'new_item' => 'Ny instruktør',
        'parent_item_colon' => 'Overordnet instruktør:',
        'search_items' => 'Søk instruktører',
        'not_found' => 'Ingen instruktører funnet',
        'not_found_in_trash' => 'Ingen instruktører funnet i søppelkurven',
        'archives' => 'instruktørliste',
        'attributes' => 'instruktørattributter',
        'featured_image' => 'Instruktørbilde',
        'set_featured_image' => 'Velg instruktørbilde',
        'remove_featured_image' => 'Fjern',
        'use_featured_image' => 'Bruk bilde',
        'insert_into_item' => 'Sett inn',
        'uploaded_to_this_item' => 'Lastet opp til denne instruktøren',
        'filter_items_list' => 'Filtrer instruktørliste',
        'filter_by_date' => 'Filtrer på dato',
        'items_list_navigation' => 'naviger i instruktører',
        'items_list' => 'Instruktørliste',
        'item_published' => 'Instruktør publisert',
        'item_published_privately' => 'Instruktør publisert privat',
        'item_reverted_to_draft' => 'Instruktør gjort om til kladd',
        'item_scheduled' => 'Instruktør planlagt',
        'item_updated' => 'Instruktør oppdatert',
        'item_link' => 'Link',
        'item_link_description' => 'Link til instruktør',
    ),
    'public'        => true,
    'has_archive'   => true,
    'show_in_rest'  => true,
    //'show_in_menu'      => 'edit.php?post_type=kurs',
    'show_in_admin_bar' => true,
    'menu_icon'     => 'dashicons-groups',
    'supports'      => array('title', 'editor', 'excerpt', 'thumbnail','custom-fields'),
    'taxonomies'    => array('coursecategory', 'course_location'),
    'rewrite'       => array('slug' => $instruktor ),
    'delete_with_user' => false,
));
