<?php
// HUSK BEDRIFTSVARIABLER

if (!defined('ABSPATH')) {
    exit;
}

$url_options = get_option('kag_seo_option_name');
$kurs = !empty($url_options['ka_url_rewrite_kurs']) ? $url_options['ka_url_rewrite_kurs'] : 'kurs';
$instruktor = !empty($url_options['ka_url_rewrite_instruktor']) ? $url_options['ka_url_rewrite_instruktor'] : 'instruktor';

// CPT Kurs
register_post_type('ka_course', array(
    'labels' => array(
        'name' => 'KA kurs',
        'singular_name' => 'KA kurs',
        'menu_name' => 'Kurs',
        'all_items' => 'Alle kurs',
        'edit_item' => 'Rediger kurs',
        'view_item' => 'Vis KA kurs',
        'view_items' => 'Vis KA kurs',
        'add_new_item' => 'Legg til KA kurs',
        'add_new' => 'Legg til KA kurs',
        'new_item' => 'Nytt KA kurs',
        'parent_item_colon' => 'Overordnet KA kurs:',
        'search_items' => 'Søk KA kurs',
        'not_found' => 'Ingen KA kurs funnet',
        'not_found_in_trash' => 'Ingen KA kurs funnet i søppelkurven',
        'archives' => 'KA kursliste',
        'attributes' => 'KA kursattributter',
        'featured_image' => 'Hovedbilde',
        'set_featured_image' => 'Velg hovedbilde',
        'remove_featured_image' => 'Fjern',
        'use_featured_image' => 'Bruk bilde',
        'insert_into_item' => 'Sett inn',
        'uploaded_to_this_item' => 'Lastet opp til dette kurset',
        'filter_items_list' => 'Filtrer kursliste',
        'filter_by_date' => 'Filtrer på dato',
        'items_list_navigation' => 'naviger i kurs',
        'items_list' => 'Kursliste',
        'item_published' => 'KA kurs publisert',
        'item_published_privately' => 'KA kurs publisert privat',
        'item_reverted_to_draft' => 'KA kurs gjort om til kladd',
        'item_scheduled' => 'KA kurs planlagt',
        'item_updated' => 'KA kurs oppdatert',
        'item_link' => 'Link',
        'item_link_description' => 'Link til kurs',
    ),
    'public'        => true,
    'has_archive'   => false,
    'show_in_rest'  => true,
    'show_in_admin_bar' => false,
    'show_in_nav_menus' => true,
    'show_in_menu'  => 'kursagenten',
    'menu_icon'     => 'dashicons-welcome-learn-more',
    'supports'      => array('title', 'editor', 'excerpt', 'thumbnail','custom-fields','page-attributes'),
    'taxonomies'    => array('ka_coursecategory', 'ka_course_location'),
    'rewrite'       => array('slug' => $kurs, 'with_front' => false),
    'hierarchical'  => true,
    'parent_item_colon' => 'Hovedkurs:',
    'delete_with_user' => false,
));

// CPT Kursdato
register_post_type('ka_coursedate', array(
    'labels' => array(
        'name' => 'Kursdatoer',
        'singular_name' => 'Kursdato',
        'menu_name' => 'Kursdatoer',
        'all_items' => 'Kursdatoer',
        'edit_item' => 'Rediger kursdato',
        'view_item' => 'Vis kursdato',
        'view_items' => 'Vis kursdato',
        'add_new_item' => 'Legg til kursdato',
        'add_new' => 'Legg til kursdato',
        'new_item' => 'Ny kursdato',
        'search_items' => 'Søk i kursdato',
        'not_found' => 'Ingen kursdatoer funnet',
        'not_found_in_trash' => 'Ingen kursdatoer funnet i søppelkurven',
        'archives' => 'kursdato arkiv',
        'attributes' => 'Kursdato attributter',
        'set_featured_image' => 'Velg hovedbilde',
        'remove_featured_image' => 'Fjern hovedbilde',
        'use_featured_image' => 'Bruk som hovedbilde',
        'insert_into_item' => 'Sett inn i kursdato',
        'uploaded_to_this_item' => 'Lastet opp til kursdato',
        'filter_items_list' => 'Filtrer kursdato liste',
        'filter_by_date' => 'Filtrer kursdato på dato',
        'items_list_navigation' => 'Kursdato listenavigasjon',
        'items_list' => 'Kursdato liste',
        'item_published' => 'Kursdato publisert.',
        'item_published_privately' => 'Kursdato publisert privat.',
        'item_reverted_to_draft' => 'Kursdato gjort om til kladd.',
        'item_scheduled' => 'Kursdato planlagt.',
        'item_updated' => 'Kursdato oppdatert.',
        'item_link' => 'Kursdato link',
        'item_link_description' => 'Link til en kursdato.',
    ),
    'public'            => false,
    'show_ui'           => true,
    'show_in_menu'      => 'edit.php?post_type=ka_course',
    'show_in_admin_bar' => false,
    'show_in_rest'      => true,
    'menu_icon'         => 'dashicons-calendar-alt',
    'supports'          => array('title', 'custom-fields'),
    'taxonomies'        => array('ka_course_location', 'ka_coursecategory'),
    'rewrite'           => false,
    'publicly_queryable'=> false,
    'query_var'         => false,
    'delete_with_user'  => false,
));
